### ISSUE TITLE
Criar suporte a Cards (fichas catalográficas)

### ISSUE THREAD

**Issue by GioSF** [Archeion-Project/api#1]
Criar model e [resource controller](https://laravel.com/docs/8.x/controllers#api-resource-routes) (específico para api) para Cards.
Atributos de Card:

- subject: texto, nullable
- journal_id: int, nunable
- date_issue, date, nullable
- duration_issue: date, nullable
- abstract: text, nullable
- comment: text, nullable
- issue: text, nullable

**Comment by giosf** [comment]
Implementado
