### ISSUE TITLE
Criar suporte a organizations

### ISSUE THREAD

**Issue by GioSF** [Archeion-Project/api#18]
Criar model, controller, migration e route para organization.
Atributos de organization:

- slug: text, not nullable
- description: text, nullable
- google_maps_link: text, nullable 

Atualizar/checar relações:

- organization hasOne ResourceProfile
- journals belongsTo organization
- cards belongsTo organization
- news belongsTo organization

**Comment by giosf** [comment]
Implementada

**Comment by giosf** [comment]
Implementada
