### ISSUE TITLE
Criar suporte a Journals

### ISSUE THREAD

**Issue by GioSF** [Archeion-Project/api#2]
Criar model e [resource controller](https://laravel.com/docs/8.x/controllers#api-resource-routes) (específico para api) para Journals.

Atributos de Journal:

localization: text, nullable
title: text, nullable
printing: text, nullable
initials: text, nullable
idiom: text, nullable;
creation_date: datetime, nullable;
end_date: datetime, nullable

**Comment by giosf** [comment]
Implementado

**Comment by giosf** [comment]
Implementado
