### ISSUE TITLE
Criar suporte a File

### ISSUE THREAD

**Issue by GioSF** [Archeion-Project/api#4]
Criar model e [resource controller](https://laravel.com/docs/8.x/controllers#api-resource-routes) (específico para api) para Files.
Atributos de files:

- title: text, required
- description: text, required
- filepath: text 
- hash_name: text, required

Não para esta issue: validação de formato de arquivo, tamanho de arquivo, dimensão (de imagem)

**Comment by giosf** [comment]
Implementado
